// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"


namespace BaseGameplayTags
{
	//Movement
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PlaneLook);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload);	
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_FireModeSelect);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ZoomIn);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Leaning);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Inventory);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ExitPlane);
	

	
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ActionMode_Stand);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ActionMode_Crouch);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ActionMode_Prone);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ActionMode_Rifle);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ActionMode_Unarmed);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ActionMode_Melee);
	
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Slot_Primary);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Slot_Secondary);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Slot_SideArm);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Slot_Melee);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Slot_Throwable);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Slot_Punch);

	//Item
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Armor);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Backpack);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Helmet);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Primary);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Secondary);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_SideArm);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Melee);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Throwable);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Slot_Punch);
	
	// Weapon
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Primary);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Secondary);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_SideArm);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Melee);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Throwable);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Punch);
	
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Gear);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Gear_Armor);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Gear_Backpack);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Gear_Helmet);

	// Weapon Parts
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Magazine);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Sight);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Sight_Rifle);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Grip);
	
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Muzzle);
	
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Muzzle_Suppressor_AR);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Muzzle_Suppressor_GROZA);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Muzzle_Suppressor_SR);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Muzzle_Suppressor_SMG);
	
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Parts_Stock);
	


	// WeaponState
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_FireBlock);

	
	// FireMode
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_FireMode_Single);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_FireMode_Burst);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_FireMode_Auto);

	// Status
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_WeaponSpeedPenalty);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_BluezoneDamage);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Buff_ImmuneBluezone);

	// GameplayEvent
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ReloadDone);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_FireModeSelectDone);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Player_HitReact);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Player_Dead);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_WeaponAttach);
	
	// Shared
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Data_GunDamage);


	//Vehicle
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_Throttle);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_Break);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_HandBreak);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_ToggleCamera);
	DEDICATED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Vehicle_Steering);

	
}

